name: Bots
version: 1.0.0
main: chbya\Bots\Main
api: [5.0.0]
author: chbya

events:
  - PlayerJoinEvent

commands:
  arena:
    description: Manage PvP bot arenas
    permission: pvpbots.arena.setup
  queue:
    description: Queue for a PvP bot match
    permission: pvpbots.queue
  settings:
    description: Configure PvP bot settings
    permission: pvpbots.settings

permissions:
  pvpbots.arena.setup:
    description: Allows setting up PvP bot arenas
    default: op
  pvpbots.queue:
    description: Allows queueing for PvP bot matches
    default: true
  pvpbots.settings:
    description: Allows configuring PvP bot settings
    default: true